version : '3.9'

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=youtube
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
        ports:
            - 5432:5432
    web:
        build: .
        command:
            - /bin/bash
            - -c
            - |
                python manage.py migrate
                python manage.py wait_for_db
                python manage.py runserver 127.0.0.1:8000
        ports:
            - 8000:8000
        depends_on:
            - db