# Generated by Django 3.2.4 on 2021-07-03 09:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=5000)),
                ('publishedat', models.DateTimeField()),
                ('thumbnails', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
